# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Investments 305
tagline:          
description:      'A course website'
url:              
baseurl:          /

author:
  name:           'LB'
  url:            https://twitter.com/investments305

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
